name: Build e Deploy GXSteel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências Front-end
        run: |
          cd "GXSteel Front-end"
          npm install
      - name: Build Front-end
        run: |
          cd "GXSteel Front-end"
          npm run build

  test-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar dependências Back-end
        run: |
          cd "GXSteel Back-end"
          npm install
      - name: Testar rotas básicas (sem MongoDB)
        run: |
          echo "Executando teste fake (sem dependência de MongoDB)"
          # Aqui você pode rodar um teste mock ou simplesmente checar se arquivos existem:
          ls "GXSteel Back-end"
      - name: Listar arquivos do build
        run: ls -lh "GXSteel Front-end/build"


  deploy:
    needs: [build-front, test-back]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Front-end
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 15029
          source: "GXSteel Front-end/build/"
          target: "/var/www/html/gxsteel/"

      - name: Deploy Back-end (sem .env)
        run: |
          tar --exclude='.env' -czf backend.tar.gz -C "GXSteel Back-end" .
        shell: bash

      - name: Copiar Back-end pro servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 15029
          source: "backend.tar.gz"
          target: "/tmp/backend.tar.gz"

      - name: Extrair e substituir Back-end no servidor (sem .env)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 15029
          script: |
            cd /opt/gxsteel-backend
            find . -type f ! -name '.env' -delete
            tar -xzf /tmp/backend.tar.gz -C .
            rm /tmp/backend.tar.gz

      - name: Reiniciar container docker do back-end
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 15029
          script: |
            docker restart gxsteel-backend
